---
http_interactions:
- request:
    method: post
    uri: http://tpt2.dev.cwds.io:8084/rfa-1a-forms?token=null
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      date:
      - Mon, 10 Jul 2017 18:38:24 GMT
      content-type:
      - application/json
      content-length:
      - '77'
    body:
      encoding: UTF-8
      string: |-
        {
          "id" : 47,
          "is_initial_application" : true,
          "is_other_type" : false
        }
    http_version: 
  recorded_at: Mon, 10 Jul 2017 18:38:24 GMT
recorded_with: VCR 3.0.3
